### ISSUE TITLE
pitaya-websocket-client

### ISSUE THREAD

**Issue by ruifly2012** [topfreegames/pitaya#1]
pitaya-websocket-client page not found

**Comment by cscatolini** [comment]
Hi @ruifly2012. Pitaya is currently under heavy development and we haven't had the time to update the docs and links properly. I will keep this issue open and let you know when we fix this. If you need a websocket client right away it is possible that [nano-websocket-client](https://github.com/lonnng/nano-websocket-client) is still compatible, but I have not tested it.

**Comment by felipejfc** [comment]
@cscatolini it is but it does not feature new things that we are doing such as protobuf as a part of the protocol

**Comment by ruifly2012** [comment]
can i use  nano-websocket-client to connect the server now?

**Comment by felipejfc** [comment]
you can @ruifly2012, but be sure to set pitaya.handler.messages.compression config to false, e.g.
```
	config := viper.New()
	config.Set("pitaya.handler.messages.compression", false)
	pitaya.Configure(true, "chat", pitaya.Standalone, map[string]string{}, config)
	pitaya.Start()
```
and also, protobuf will not work because it's not implemented in nano-ws-client, you have to use json serializer
```
	s := json.NewSerializer()
	pitaya.SetSerializer(s)
```

let us know if that worked for you,

best!

**Comment by ruifly2012** [comment]
thanks

**Comment by landbed** [comment]
any updates for js client with protobuf support?
