### ISSUE TITLE
client does not seem to work

### ISSUE THREAD

**Issue by landbed** [topfreegames/pitaya#105]
1, start pitaya:

https://github.com/topfreegames/pitaya/commit/d05957848e98c17f4ab7435802d8cf24a81ab6b6

```
$ git clone https://github.com/topfreegames/pitaya.git
$ go run pitaya/examples/demo/chat/main.go
......
INFO[0000] all modules started!                          source=pitaya
```

2.1, pitaya-cli

```
$ go get -u github.com/topfreegames/pitaya-cli
$ pitaya-cli
>>> connect 127.0.0.1:3250
Using json client
Failed to connect!
Error: tls: first record does not look like a TLS handshake
```

2.2, pitaya-cli

https://github.com/topfreegames/pitaya-cli/commit/50f16b50e83d17f0cfcf36410b71fedc42bd58da

```
$ git clone https://github.com/topfreegames/pitaya-cli.git
```

modify

```
func connect(addr string) error {
	if err := pClient.ConnectTo(addr); err != nil {
		return err
	}

	return nil
}
```

```
$ go run pitaya-cli/main.go
>>> connect 127.0.0.1:3250
Using json client
ERRO[0001] error decoding packet from server: wrong packet type
panic: runtime error: index out of range

goroutine 1 [running]:
/pitaya/client.(*Client).handleHandshakeResponse(0xc000225b00, 0x0, 0x0)
/pitaya@v0.14.3/client/client.go:147 +0x5aa
/pitaya/client.(*Client).handleHandshake(0xc000225b00, 0xa, 0xc0001e35c0)
/pitaya@v0.14.3/client/client.go:375 +0x4c
/pitaya/client.(*Client).ConnectTo(0xc000225b00, 0xc0001a2b20, 0xe, 0x0, 0xc000225b00)
/pitaya@v0.14.3/client/client.go:361 +0x11f
```

**Comment by andrehp** [comment]
Hi landbed, thanks for your interest in Pitaya!

I believe this example isn't working with pitaya-cli because the server starts a websocket acceptor, which pitaya-cli can't connect to. If you want to use pitaya-cli you can modify the code to start a TCP acceptor instead, or run a different demo, such as the cluster one.

**Comment by felipejfc** [comment]
it would be simple enough to add ws support to pitaya-cli, if we have the server support I think that we should add to the cli as well... what do you think @andrehp ?

**Comment by andrehp** [comment]
It should be simple enough to add support to ws to pitaya-cli. But given that libpitaya does not support ws currently I don't know if it would be very useful

**Comment by felipejfc** [comment]
maybe we should remove the support on the server meanwhile libpitaya doesn't support it then...
also, we should update all the examples to use TCP

**Comment by landbed** [comment]
@andrehp @felipejfc 

Thanks! ws support is useful!!!
