### ISSUE TITLE
how can i send to data when i  send by go client

### ISSUE THREAD

**Issue by srlemon** [topfreegames/pitaya#121]
i try it in go client:
   	
![image](https://user-images.githubusercontent.com/44766084/69411290-a167e080-0d47-11ea-8082-a8d78e5b483e.png)

but  pitaya-decode size  int function bytesToInt() is  to big, always more than  buff.Len()

![image](https://user-images.githubusercontent.com/44766084/69410989-1555b900-0d47-11ea-8eed-46cf1a692b00.png)

so how can i  send data, thanks

**Comment by leohahn** [comment]
Could you please give more information on what you are trying to do? It is not clear by the code samples what is your objective.

**Comment by srlemon** [comment]
i run a server with this project ,and i try do send message  by golang client, but i don‘t know how do send message format

**Comment by felipejfc** [comment]
Hi @srlemon, the current purpose of the golang client is currently testing. For using in production I suggest taking a look at the c++ implementation and bindings [here](https://github.com/topfreegames/libpitaya)

**Comment by srlemon** [comment]
@felipejfc thanks

**Comment by felipejfc** [comment]
no problem! closing
