### ISSUE TITLE
Cannot send messages larger than 2048 bytes

### ISSUE THREAD

**Issue by bytemode** [topfreegames/pitaya#122]
https://github.com/topfreegames/pitaya/blob/287b60e35ecae869b29d87df0b782969b4bf0c09/service/handler.go#L166

Cannot send messages larger than 2048 bytes. 
Sending a message greater than 2048 results in an error， It's pretty certain。

`buf := make([]byte, 2048)`   Unable to read the full message causing an error
This code needs to be modified to read all the message contents at once.

**Comment by felipejfc** [comment]
2048 is pretty much for mobile clients (that's our current usage), what's the use case for the client to send more than 2kb information on a request?
I think we can make this configurable...

**Comment by bytemode** [comment]
we send same big message, eg,ranking list，task list，activity list , configuration data.
The message size is 16MB, which is the case when the message is designed。

**Comment by felipejfc** [comment]
I suggest you make a PR making the buffer configurable. Still, I think you should think on how to make the messages your clients are sending to de server smaller...

**Comment by felipejfc** [comment]
@bytemode this will be solved by #124
