### ISSUE TITLE
Move from dep to go modules?

### ISSUE THREAD

**Issue by marcosnils** [topfreegames/pitaya#128]

**Comment by felipejfc** [comment]
It currently supports both, do you think we should remove dep support? I'm afraid it would break some builds in other projects that use it...

**Comment by marcosnils** [comment]
Well.. `make setup` target still points to `dep`. And dep seems to be outdated since it can't be installed anymore with `go get -u github.com/golang/dep/cmd/dep` and issues (https://github.com/golang/dep/issues/2223) don't seem to be resolved. I'd vote to move away from `dep`.
