### ISSUE TITLE
Here are some questions about packet loss

### ISSUE THREAD

**Issue by suntianji123** [topfreegames/pitaya#131]
func (c *Client) readPackets(buf *bytes.Buffer) ([]*packet.Packet, error) {
	// listen for sv messages
	data := make([]byte, 1024)
	n := len(data)
	var err error

	for n == len(data) {
		n, err = c.conn.Read(data)
		if err != nil {
			return nil, err
		}
		buf.Write(data[:n])
	}
	packets, err := c.packetDecoder.Decode(buf.Bytes())
	if err != nil {
		logger.Log.Errorf("error decoding packet from server: %s", err.Error())
	}
	totalProcessed := 0
	for _, p := range packets {
		totalProcessed += codec.HeadLength + p.Length
	}
	buf.Next(totalProcessed)

	return packets, nil
}

If the read byte array is a complete packet and an incomplete packet, it will cause the data of the incomplete packet to be lost. What do you think?

**Comment by felipejfc** [comment]
Indeed It would cause the packet to be lost, however, buf should never contain incomplete packets because of the changes io this PR https://github.com/topfreegames/pitaya/pull/125/files

```
func (t *tcpPlayerConn) GetNextMessage() (b []byte, err error) {
	header, err := ioutil.ReadAll(io.LimitReader(t.Conn, codec.HeadLength))
	if err != nil {
		return nil, err
	}
	msgSize, _, err := codec.ParseHeader(header)
	if err != nil {
		return nil, err
	}
	msgData, err := ioutil.ReadAll(io.LimitReader(t.Conn, int64(msgSize)))
	if err != nil {
		return nil, err
	}
	if len(msgData) < msgSize {
		return nil, constants.ErrReceivedMsgSmallerThanExpected
	}
	return append(header, msgData...), nil
}
```

The GetNextMessage implementation of the acceptor you are using should never return any incomplete packet.

**Comment by suntianji123** [comment]
The readPackets function is not modified in the pitaya-cli project

**Comment by suntianji123** [comment]
> Indeed It would cause the packet to be lost, however, buf should never contain incomplete packets because of the changes in this PR https://github.com/topfreegames/pitaya/pull/125/files
> 
> ```
> func (t *tcpPlayerConn) GetNextMessage() (b []byte, err error) {
> 	header, err := ioutil.ReadAll(io.LimitReader(t.Conn, codec.HeadLength))
> 	if err != nil {
> 		return nil, err
> 	}
> 	msgSize, _, err := codec.ParseHeader(header)
> 	if err != nil {
> 		return nil, err
> 	}
> 	msgData, err := ioutil.ReadAll(io.LimitReader(t.Conn, int64(msgSize)))
> 	if err != nil {
> 		return nil, err
> 	}
> 	if len(msgData) < msgSize {
> 		return nil, constants.ErrReceivedMsgSmallerThanExpected
> 	}
> 	return append(header, msgData...), nil
> }
> ```
> 
> The GetNextMessage implementation of the acceptor you are using should never return any incomplete packet.

The readPackets function is not modified in the pitaya-cli project. Can you update this function?

**Comment by felipejfc** [comment]
can you submit a PR?
