### ISSUE TITLE
Connector logs "Error reading next available message: invalid header" on player disconnection

### ISSUE THREAD

**Issue by renatoaf** [topfreegames/pitaya#138]
**Version used:** v1.1.0

Connector keeps spamming this "Error reading next available message: invalid header" message:

{"file":"/home/jenkins/jobs/tennis-build-backend/builds/988/pkg/mod/github.com/topfreegames/pitaya@v1.1.0/service/handler.go:186","func":"github.com/topfreegames/pitaya/service.(*HandlerService).Handle","level":"error","msg":"Error reading next available message: invalid header","server":"connector","source":"tennis","time":"2020-04-22T01:06:03Z”}
Is that expected or are we doing something wrong? Apparently it happens when a user disconnects. Doesn’t seem to cause any harm, but if this is not really an unexpected error, we could make it a debug log.

**Related code:** https://github.com/topfreegames/pitaya/blob/3d3b62a19e45b2f98847424e53ae3f7ef255502a/service/handler.go#L186

**Comment by felipejfc** [comment]
Does it stop logging eventually or it just keeps logging this until we kill the server?

**Comment by chgz** [comment]
i remember this.
a client disconnect will get once.

my plan：
1. allocate _head_ and _body_ []byte in advance for each tcpPlayerConn  and reuse them; 
2. replace io.ReadAll with io.readFull to complete packet reading. 
@felipejfc

**Comment by renatoaf** [comment]
@felipejfc it logs an error each time a client disconnects - doesn't stop

We ignored this log on filebeat
