### ISSUE TITLE
Is it suitable for an MMO Game?

### ISSUE THREAD

**Issue by tutumagi** [topfreegames/pitaya#140]
I am writing an MMO game server with golang for five months already. Then I find the `pitaya` repo. And It's very good.
But an MMO game often has status synchronization with surrounding players. 
I want to use the `proto` design and `RPC` design which used in the `pitaya` repo. 
But  I'm not sure it's suitable for an MMO Game. 
Anyone can give me suggestions?

**Comment by leohahn** [comment]
Hmm, I never thought about the possibility of an MMO game. However, I think it is possible. Do you plan to implement the gameplay using pitaya?

What are the features you're going to need from the server?

**Comment by tutumagi** [comment]
Do you plan to implement the gameplay using pitaya?

**Comment by tutumagi** [comment]
> Do you plan to implement the gameplay using pitaya?

Just use some features. Such as the cluster design, proto design.
But I don't know how to add the position synchronization in the area of interest management.

**Comment by felipejfc** [comment]
It is totally possible to build it with Pitaya. For a MMO you will probably
route users to different backend servers that would then run the
simulation, Pitaya allows you to create the routing and manage user
sessions etc. But the actual logic of position changes and the state of the
“world” are independent from Pitaya.

**Comment by tutumagi** [comment]
OK.  I will comment soon after my game deploys.

**Comment by tutumagi** [comment]
Is it suitable to add a DB server for all DB write/read work?
How do you code the DB server? With pitaya? Or use an Independent service?

**Comment by felipejfc** [comment]
> Is it suitable to add a DB server for all DB write/read work?
> 
> How do you code the DB server? With pitaya? Or use an Independent service?

Hi @tutumagi, sure it is... we usually use some well-known DB from within Pitaya. Usually Postgres or Redis, but can be any depending on your workload.

**Comment by tutumagi** [comment]
@felipejfc Thanks. Is there a gitter/slack for the repo？ Maybe I often ask questions. 😄

**Comment by felipejfc** [comment]
Right now there isn't, but feel free to just open an issue whenever you need help.

best!

**Comment by tutumagi** [comment]
Can I hold the different services in the same server?
Example
```go
        // hold the components
        // And use them in different service.  like this:  connector.Foo() { login.Bar() }
        connector :=&services.Connector{}
        connectorRemote := &services.ConnectorRemote{}
        login := &services.Login{}
	pitaya.Register(connector,
		component.WithName("connector"),
		component.WithNameFunc(strings.ToLower),
	)
	pitaya.RegisterRemote(connectorRemote,
		component.WithName("connectorremote"),
		component.WithNameFunc(strings.ToLower),
	)

	pitaya.Register(login,
		component.WithName("login"),
		component.WithNameFunc(strings.ToLower),
	)
````
