### ISSUE TITLE
result of GetServersByType() 

### ISSUE THREAD

**Issue by chgz** [topfreegames/pitaya#141]
help: 
![image](https://user-images.githubusercontent.com/46476616/93758286-ba2c7580-fc3a-11ea-8868-2e8ed41062a1.png)

Why return map instead of slice? 
If slice , the defaultrouter() can be O(1)  instead of O(n)

**Comment by felipejfc** [comment]
Great point, it is a map because I thought it would be easier for the callee to use the answer in this way... But it is indeed harming defaultrouter, I'm gonna change it

**Comment by felipejfc** [comment]
I did some digging and it's not that simple actually, we would need to maintain a slice of servers or slice of server keys for doing this more performatic and then keep updating it, inserting/deleting servers as we do with the maps

**Comment by chgz** [comment]
i add a method  GetServersByTypeWithSlice()  to  ServiceDiscovery Interface.

**Comment by chgz** [comment]
I added a method GetServersByTypeWithSlice() to ServiceDiscovery Interface. 
It is the same as GetServersByType() expect for the return value type.
The defaultrouter can use it.
And I have extended other routing strategies to support rolling updates of stateless servers.

my local repo has been modified too much and difficult to submit a pr.  Sorrry!
