### ISSUE TITLE
How to call the local service method?

### ISSUE THREAD

**Issue by tutumagi** [topfreegames/pitaya#144]
How to call the local service method?
Can I hold the different services in the same server?
Example
```go
        // hold the components
        // And use them in different service.  like this:  connector.Foo() { login.Bar() }
        connector :=&services.Connector{}
        connectorRemote := &services.ConnectorRemote{}
        login := &services.Login{}
	pitaya.Register(connector,
		component.WithName("connector"),
		component.WithNameFunc(strings.ToLower),
	)
	pitaya.RegisterRemote(connectorRemote,
		component.WithName("connectorremote"),
		component.WithNameFunc(strings.ToLower),
	)

	pitaya.Register(login,
		component.WithName("login"),
		component.WithNameFunc(strings.ToLower),
	)
````

_Originally posted by @tutumagi in https://github.com/topfreegames/pitaya/issues/140#issuecomment-699861789_

**Comment by felipejfc** [comment]
the handlers are supposed to be called by clients, when they issue a call with the route connector.foo for example, pitaya will route the request to the method.

if you mean to call them by yourself, maybe it's not a handler what you want...
