### ISSUE TITLE
The import address of clientv3 needs to be updated

### ISSUE THREAD

**Issue by codingcn** [topfreegames/pitaya#147]
`github.com/coreos/etcd/clientv3` is out.

please use `go.etcd.io/etcd/clientv3`.

**Comment by greatcat-taihe** [comment]
Please fix it. It will compile error when use new version grpc library.
../../Documents/go/pkg/mod/github.com/coreos/etcd@v3.3.9+incompatible/clientv3/health_balancer.go:54:10: undefined: grpc.Address

**Comment by codingcn** [comment]
https://github.com/etcd-io/etcd/issues/12124
