### ISSUE TITLE
Notify will print "Failed to serialize return: protobuf: convert on wrong type value"

### ISSUE THREAD

**Issue by greatcat-taihe** [topfreegames/pitaya#149]
I use nats rpc client and protobuf,  notify handler always print error "Failed to serialize return: protobuf: convert on wrong type value"
My pitaya version is v1.1.2

**Comment by felipejfc** [comment]
were you able to fix this?

**Comment by leonardo2204** [comment]
@greatcat-taihe Since it's been almost 4 months, I'll close this issue. If it happens again or you need further assistance, don't hesitate to open a new issue!

Thanks!
