### ISSUE TITLE
What is the difference between component and module?

### ISSUE THREAD

**Issue by NicholasChan1025** [topfreegames/pitaya#156]
Hi guys
What is the difference between component and module?
I didn't find in the documentation a description of the application scenarios of component and module in the project, so I don't quite understand the difference between them, especially since their interface methods are the same.
For example, the database access, should it be component or module, I hope to get your answer

**Comment by felipejfc** [comment]
Components are internal structures, for extending pitaya you should use modules. The are plenty ways to access a database, I would put it into a Business Logic Layer of the project that's using pitaya. But if you want to make it a part of pitaya, to leverage the hooks (beforeStart, afterStart, etc), then, do it with a moduule

**Comment by NicholasChan1025** [comment]
Thank you for your answer
I close this question
