### ISSUE TITLE
Confuse on protoc and grpc version

### ISSUE THREAD

**Issue by greatcat-taihe** [topfreegames/pitaya#168]
I setup a new project and found that etcd package not compatible with new version of grpc.
I must add this ```replace google.golang.org/grpc => google.golang.org/grpc v1.26.0``` force use grpc version 1.26.0
so what protoc version should I use to generate my protobuf files?

**Comment by rsafonseca** [comment]
Hey @greatcat-taihe 
Pitaya v1.1.6+ is now using grpc 1.29.1 :)

**Comment by greatcat-taihe** [comment]
> Hey @greatcat-taihe
> Pitaya v1.1.6+ is now using grpc 1.29.1 :)

cool, I upgrade grpc to 1.29.1. protoc-gen-go to 1.5.0, protoc-gen-go-grpc to 1.31.1
