### ISSUE TITLE
Do i need write test in long connect game server?

### ISSUE THREAD

**Issue by Sun-FreePort** [topfreegames/pitaya#169]
I learn Go by [Learn Go with tests](https://quii.gitbook.io/learn-go-with-tests/), and I love auto test -- very safe!

But, my work is PHP in Web server, write unit/API test in HTTP server is easy, so, i want ask:

In websocket game, need write test? if is sure, how write and test?

**Comment by felipejfc** [comment]
Yes, the best practice would be write the tests.

with pitaya you already have the connector part tested (e.g. websocket), then you need only to write business logic and then you choose how to test it, with unit testing and maybe also integration tests, depending on your needs.

I think we could benefit from an example containing tests to give some directions...

best!

**Comment by Sun-FreePort** [comment]
Thank you! i find it.

I will try at tonight. this a new experience for me, XD
