### ISSUE TITLE
how to unify code types

### ISSUE THREAD

**Issue by ikerlin** [topfreegames/pitaya#173]
how can change the func error response message code type to int?

```go
type CommonResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Manager struct {
	component.Base
}

func (m *Manager) Login(ctx context.Context) (*CommonResponse, error) {
     if ERR {
          return nil, ERR
    }
    return &CommonResponse{}, nil
}
```

**Comment by felipejfc** [comment]
I didn't get the question, can you clarify?

**Comment by ikerlin** [comment]
> I didn't get the question, can you clarify?

my CommonResponse.Code is int, but when Login return error, the response code is string

**Comment by felipejfc** [comment]
I see, it's because we've decided to go with error's in the format like PIT-500 and so on.
Well, you would need to change how we deal with erros in this file https://github.com/topfreegames/pitaya/blob/master/errors/errors.go
