### ISSUE TITLE
how to use pitaya-cli test cluster-protobuf-backend-example?

### ISSUE THREAD

**Issue by yilinershi** [topfreegames/pitaya#199]
I see the demo cluster_protobuf, but I don’t known how to use pitaya-cli connect this demo. I move to the pitaya-cli project, I see the infomation:
```
pitaya-cli -docs connector.docsHandler.docs
>>> push connector.playerHandler.matchfound protos.FindMatchPush
>>> connect localhost:30124
>>> request connector.playerHandler.create
>>> request connector.playerHandler.findmatch {"RoomType":"xxxx"}
```

but this without an demo.  sad cry.

I suggest In the demo cluster_protobuf, you can give us a pitaya-cli test  example .

**Comment by felipejfc** [comment]
I have plans to move the cli to this repo as well and then improve the docs and examples

**Comment by yilinershi** [comment]
Hats off to your team and your great job . 
         ----love from the east part of this planet

**Comment by yilinershi** [comment]
@felipejfc Hats off to your team and your great job ----love from the east part of this planet
