### ISSUE TITLE
How to set and get struct from session!

### ISSUE THREAD

**Issue by yilinershi** [topfreegames/pitaya#202]
now look at a example below:
```go
type Test struct {
	A string
	B string
}

func SetTestToSession(s *session.Session, t *Test) {
	s.Set("test", t)
}

func GetTestFromSession(s *session.Session) *Test {
	t := s.Get("test")
	return t.(*Test)  //it'll error here
}

//test set struct into session
t := &Test{
	A: "aaaaaa",
	B: "bbbbb",
}
SetTestToSession(s, t)

//test get struct from session 
target:=GetTestFromSession(s)    
```
in this example, if  you get data from session ,it'll be error, you set a struct into session, but when you want get a struct from session, the data can not assert to struct .

**The right way to get struct from session must turn the data to map[string]interface{} first** ，here is the example
``` go
import "github.com/goinggo/mapstructure"

type Test struct {
	A string
	B string
}

func SetTestToSession(s *session.Session, t *Test) {
	s.Set("test", t)
}

func GetTestFromSession(s *session.Session) *Test {
	//step1: here must turn testData to map[string]interface{} first
	testData := s.Get("test").(map[string]interface{})

	//step2: turn map[string]interface{} to your target suruct
	t := &Test{}
	if err := mapstructure.Decode(testData, t); err != nil {
		fmt.Println(err)
	}
	return t   //now it'll return the right struct 
}

//test set struct into session
t := &Test{
	A: "aaaaaa",
	B: "bbbbb",
}
SetTestToSession(s, t)

//test get struct from session 
target:=GetTestFromSession(s)    
```

**Comment by felipejfc** [comment]
You mean when you set in a backend server and then try to get into another server or in a frontend server, right?

I just created the following test and it runs fine:

```
func TestSessionStruct(t *testing.T) {
	t.Parallel()

	tables := []struct {
		name string
		val  *someStruct
	}{
		{"existent", &someStruct{A: 1, B: "somestring"}},
		{"unexistent", nil},
	}

	for _, table := range tables {
		t.Run(table.name, func(t *testing.T) {
			ss := New(nil, true)
			assert.NotNil(t, ss)

			if table.val != nil {
				err := ss.Set("key", table.val)
				assert.NoError(t, err)
				assert.NotEmpty(t, ss.data)
				val := ss.Get("key")
				assert.Equal(t, table.val, val.(*someStruct))
			} else {
				val := ss.Value("key")
				assert.Nil(t, val)
			}

		})
	}
}
```

However, if I try to get the value on another session (after being sent by networking) then probably it won't work, because we send it marshalled as json. Then I imagine we would observe the behavior you're describing.
We could probably have a better golang experience if we used gob to encode and send by network, however, the reason we marshal as a json is that you can maintain compatibility with other languages.

**Comment by yilinershi** [comment]
> You mean when you set in a backend server and then try to get into another server or in a frontend server, right?
> 
> I just created the following test and it runs fine:
> 
> ```
> func TestSessionStruct(t *testing.T) {
> 	t.Parallel()
> 
> 	tables := []struct {
> 		name string
> 		val  *someStruct
> 	}{
> 		{"existent", &someStruct{A: 1, B: "somestring"}},
> 		{"unexistent", nil},
> 	}
> 
> 	for _, table := range tables {
> 		t.Run(table.name, func(t *testing.T) {
> 			ss := New(nil, true)
> 			assert.NotNil(t, ss)
> 
> 			if table.val != nil {
> 				err := ss.Set("key", table.val)
> 				assert.NoError(t, err)
> 				assert.NotEmpty(t, ss.data)
> 				val := ss.Get("key")
> 				assert.Equal(t, table.val, val.(*someStruct))
> 			} else {
> 				val := ss.Value("key")
> 				assert.Nil(t, val)
> 			}
> 
> 		})
> 	}
> }
> ```
> 
> However, if I try to get the value on another session (after being sent by networking) then probably it won't work, because we send it marshalled as json. Then I imagine we would observe the behavior you're describing.
> We could probably have a better golang experience if we used gob to encode and send by network, however, the reason we marshal as a json is that you can maintain compatibility with other languages.

> You mean when you set in a backend server and then try to get into another server or in a frontend server, right?
**yes,I set in a backend server and then try to get into another server.** 

Thank you for your explanation.  I have learned some design ideas from this project .
