### ISSUE TITLE
SendRPCMsg 

### ISSUE THREAD

**Issue by AsukaLay** [topfreegames/pitaya#223]
SendRPCMsg err: RPC-000 rpc call internal error - Join: runtime error: invalid memory address or nil pointer dereference
remote SendRPCMsg 
what's wrong   context.properties?

**Comment by felipejfc** [comment]
how to reproduce?

**Comment by AsukaLay** [comment]
in examples  demo  cluster_protobuf
isFrontend = true  connector server
connector.go  :  
func (c *Connector) SendRPCMsg(ctx context.Context) (*protos.Reply, error) {
	ret := protos.RPCMsg{}
	err := pitaya.RPC(ctx, "room.room.join", &ret, &protos.RPCMsg{Route: "room.room.join", Msg: "123321"})
	if err != nil {
		fmt.Println("SendRPCMsg err: RPC-000", err)
		return nil, pitaya.Error(err, "RPC-000")
	}
	fmt.Println("SendRPCMsg : ", ret, ret.Msg)
	return reply(200, ret.Msg), nil
}

isFrontend = false  room server 

func (r *Room) Join(ctx context.Context) (*protos.Reply, error) {
	s := pitaya.GetSessionFromCtx(ctx)             
	fakeUID := s.ID()                              // just use s.ID as uid !!!
	err := s.Bind(ctx, strconv.Itoa(int(fakeUID))) // binding session uid 
	if err != nil {
		return nil, pitaya.Error(err, "RH-000", map[string]string{"failed": "bind"})
	}
	members, err := pitaya.GroupMembers(ctx, "room") 
	if err != nil {
		return nil, err
	}
	s.Push("onMembers", &protos.AllMembers{Members: members})                                                                
	pitaya.GroupBroadcast(ctx, "connector", "room", "onNewUser", &protos.NewUser{Content: fmt.Sprintf("New user: %d", s.ID())})
	pitaya.GroupAddMember(ctx, "room", s.UID())                                                                                 
	s.OnClose(func() {
		pitaya.GroupRemoveMember(ctx, "room", s.UID()) 
	})
	return &protos.Reply{Msg: "success"}, 
}


 s :=pitaya.GetSessionFromCtx(ctx)      session is nil


client code  
if (_client.State == PitayaClientState.Connected)
            {
                Reply response = new Reply
                {
                    Msg = "hello",
                    Code = 100
                };
                ((PitayaClient)_client).Request<Reply>("connector.sendrpcmsg", response, ResponseMsgRemote, ResponseErrorRemote);
            }

and then connector server show 
SendRPCMsg err: RPC-000 rpc call internal error - Join: runtime error: invalid memory address or nil pointer dereference
remote SendRPCMsg

**Comment by AsukaLay** [comment]
s := pitaya.GetSessionFromCtx(ctx)
ctx doesn't contain a session, are you calling GetSessionFromCtx from inside a remote

**Comment by AsukaLay** [comment]
nats_rpc_server.go
func (ns *NatsRPCServer) processMessages(threadID int) 
ctx, err := util.GetContextFromRequest(ns.requests[threadID], ns.server.ID)
func Decode(m []byte) (context.Context, error) {
	if len(m) == 0 {
		// TODO maybe return an error
		return nil, nil
	}
	mp := make(map[string]interface{}, 0)
	err := json.Unmarshal(m, &mp)
	if err != nil {
		return nil, err
	}
	ctx := FromMap(mp)

	return ctx, nil

}

Decode
<map[string]interface {}> (length: 6)
"opentracing-span":<interface {}(map[string]interface {})>)
data:<map[string]interface {}> (length: 0)
"peer.id":<interface {}(string)>)
data:"8b26c3bf-fc1a-43c9-8ec6-aca95dba343a"
"peer.service":<interface {}(string)>)
data:"connector"
"req-route":<interface {}(string)>)
data:"connector.sendrpcmsg"
"req-start-time":<interface {}(float64)>)
data:1627351827075666700
"request.id":<interface {}(string)>)
data:"akyyk7hqswWIxR3RyMeooF"

FromMap
