### ISSUE TITLE
There's something wrong with this function: etcdServiceDiscovery.GetServersByType()

### ISSUE THREAD

**Issue by tigerxuz** [topfreegames/pitaya#229]
```
ret := make(map[string]*Server, len(sd.serverMapByType))
for k, v := range sd.serverMapByType[serverType] {
	ret[k] = v
}
```
The cap value of make is not very reasonable

**Comment by gabrielcorado** [comment]
Hey, hello, I've checked the code, and you're right the initial size is wrong. Even if this won't cause any issue, I will open a PR to change it. Thanks for your contribution.
