### ISSUE TITLE
after upgrade to v2, environment not work

### ISSUE THREAD

**Issue by greatcat-taihe** [topfreegames/pitaya#244]
when v1, i use env PITAYA_CLUSTER_SD_ETCD_ENDPOINTS, PITAYA_CLUSTER_RPC_CLIENT_NATS_CONNECT, PITAYA_CLUSTER_RPC_SERVER_NATS_CONNECT.
After upgrade to pitaya v2, i must write some code like this
``` golang
	etcdConf := *config.NewDefaultEtcdServiceDiscoveryConfig()
	etcdConf.Endpoints = pitayaConf.GetStringSlice("pitaya.cluster.sd.etcd.endpoints")
	etcdConf.User = pitayaConf.GetString("pitaya.cluster.sd.etcd.user")
	etcdConf.Pass = pitayaConf.GetString("pitaya.cluster.sd.etcd.pass")
	builder.ServiceDiscovery, err = cluster.NewEtcdServiceDiscovery(etcdConf, builder.Server, builder.DieChan)
```

**Comment by henriqueoelze** [comment]
Hello @greatcat-taihe , 
Pitaya v2 is a breaking change release, as mentioned in the https://github.com/topfreegames/pitaya/issues/240.
We have in our roadmap a task to write a migration guide to help all users to migrate to it, but with that in mind, it is not compatible with Pitaya projects written with Pitaya v1.

If you prefer, you can continue to use Pitaya v1 with no problem, and we will follow the roadmap described in the issue about fixes, new features, etc.
