### ISSUE TITLE
pitaya\cluster\etcd_service_discovery.go   append nil  server 

### ISSUE THREAD

**Issue by AsukaLay** [topfreegames/pitaya#245]
pitaya\cluster\etcd_service_discovery.go
func (sd *etcdServiceDiscovery) GetServersByType(serverType string) ([]*Server, error)
ret := make([]*Server, len(m))
		for _, v := range sd.serverMapByType[serverType] {
			ret = append(ret,v)
		}

this  ret := make([]*Server, len(m))     should be  make([]*Server, 0)    len(m)  change  0
because   ret = append(ret,v)      append      
if not so    will be nil  server  append

**Comment by luizmiranda7** [comment]
Hey @AsukaLay, we're not able to find the code you're referring to. 
Could you inform the pitaya version you're using?
Also, could you better describe de issue?
