### ISSUE TITLE
level=warning msg="failed to retrieve parent span: opentracing: SpanContext not found in Extract carrier" source=pitaya

### ISSUE THREAD

**Issue by AsukaLay** [topfreegames/pitaya#246]
at pitaya\cluster func\nats_rpc_client.go     
func (ns *NatsRPCClient) Call

ctx
key = session
val=interface {}| *github.com/topfreegames/pitaya/session.Session

and after  tracing.StartSpan(ctx, "NATS RPC Call", tags, parent)

ctx
key = interface{}|cant read interface type "github.com/opentracing/opentracing-go.contextKey" not found for 0x0000d4018:no type entry found. use 'types' for a list of valid types
val=interface {}| *github.com/opentracing/opentracing-go.noopSpan

and then  log notify
level=warning msg="failed to retrieve parent span: opentracing: SpanContext not found in Extract carrier" source=pitaya

**Comment by AsukaLay** [comment]
I find that  service/handler.go
func (h *HandlerService) processMessage(a *agent.Agent, msg *message.Message) 
        ctx := pcontext.AddToPropagateCtx(context.Background(), constants.StartTimeKey, time.Now().UnixNano())
	ctx = pcontext.AddToPropagateCtx(ctx, constants.RouteKey, msg.Route)
	ctx = pcontext.AddToPropagateCtx(ctx, constants.RequestIDKey, requestID)

key = interface {}|
can't read github.com/topfreegames/pitaya/constants.propagateKey not found for 0xc00067b488:no type entry found. use 'types' for a list of valid types

**Comment by WaterSweet** [comment]
I also encountered this problem, how to fix it later?

**Comment by ddk2222-luck** [comment]
I have this problem, too. How did you solve it
