### ISSUE TITLE
Author，nice to sumbit my idea about process the message.

### ISSUE THREAD

**Issue by lopies** [topfreegames/pitaya#261]
In order to process the message, many threads are opened, but it is possible that a client message is distributed to different threads, resulting in the message order disorder, if for the character movement, it may be that the thread that arrived the message first finishes processing, the server character coordinate error, affecting some serious effects. I think the message sent from the same client(agent) to the pipe should be processed by the same thread, that's my opinion, thank you.

**Comment by Heal-the-Kids** [comment]
Strictly speaking, I can't guarantee that my first message will be processed first.

**Comment by felipejfc** [comment]
I like the idea. mind sending a PR?

**Comment by Heal-the-Kids** [comment]
I'd be happy to，But I've been busy lately
