### ISSUE TITLE
Is this project unmaintained? 

### ISSUE THREAD

**Issue by edisonwsk** [topfreegames/pitaya#262]
No progress for 2 months

**Comment by henriqueoelze** [comment]
No, it is been maintained. It is considered stable and ready to use in production, so we are not iterating over it with emphasis in this quarter, but feel free to use and open issues/pull requests if needed.

**Comment by edisonwsk** [comment]
v1 is marked as deprecated, v2 has not been officially released, we use V2, so let’s know when v2 will be officially released
