### ISSUE TITLE
 can you explain how this framework is deployed in kubernetes? 

### ISSUE THREAD

**Issue by icipiqkm** [topfreegames/pitaya#263]
Hello author, can you explain how this framework is deployed in kubernetes? What is the complete deployment process? I think it would be more attractive if there is a complete deployment example

**Comment by henriqueoelze** [comment]
Hello @icipiqkm . The framework is kube agnostic. You can use if with or without it. The idea is to use Pitaya in your backend server, but the deployment flow is your choice (That is why we don't have a fully completed example, it is out of the framework scope).

We offer a simple example of kube config [here](https://github.com/topfreegames/pitaya/tree/main/deploy/kubernetes), but you can (and should) configure as your own on your project.
