### ISSUE TITLE
piatya logrus can't print  actual call location information

### ISSUE THREAD

**Issue by fourfire** [topfreegames/pitaya#276]
l := logrus.New()
	l.SetReportCaller(true)
	l.Formatter = &logrus.TextFormatter{}
	l.SetLevel(logrus.InfoLevel)
	if *debug {
		l.SetLevel(logrus.DebugLevel)
	}
	logruswrapper.NewWithFieldLogger(l)
	pitaya.SetLogger(logruswrapper.NewWithFieldLogger(l))

Always locate in github.com/topfreegames/pitaya/blob/main/logger/logrus/logrus.go file

**Comment by echo766** [comment]
`package log

import (
	"runtime"
	"strings"
	"sync"

	"github.com/sirupsen/logrus"
)

var (

	// qualified package name, cached at first use
	logrusPackage string

	// Positions in the call stack when tracing to report the calling method
	minimumCallerDepth int

	// Used for caller information initialisation
	callerInitOnce sync.Once
)

const (
	maximumCallerDepth     = 25
	knownLogrusFrames  int = 10
)

// getPackageName reduces a fully qualified function name to the package name
// There really ought to be to be a better way...
func getPackageName(f string) string {
	for {
		lastPeriod := strings.LastIndex(f, ".")
		lastSlash := strings.LastIndex(f, "/")
		if lastPeriod > lastSlash {
			f = f[:lastPeriod]
		} else {
			break
		}
	}

	return f
}

// getCaller retrieves the name of the first non-logrus calling function
func getCaller() *runtime.Frame {
	// cache this package's fully-qualified name
	callerInitOnce.Do(func() {
		pcs := make([]uintptr, maximumCallerDepth)
		_ = runtime.Callers(0, pcs)

		// dynamic get the package name and the minimum caller depth
		for i := 0; i < maximumCallerDepth; i++ {
			funcName := runtime.FuncForPC(pcs[i]).Name()
			if strings.Contains(funcName, "getCaller") {
				logrusPackage = getPackageName(funcName)
				break
			}
		}

		minimumCallerDepth = knownLogrusFrames
	})

	// Restrict the lookback frames to avoid runaway lookups
	pcs := make([]uintptr, maximumCallerDepth)
	depth := runtime.Callers(minimumCallerDepth, pcs)
	frames := runtime.CallersFrames(pcs[:depth])

	for f, again := frames.Next(); again; f, again = frames.Next() {
		pkg := getPackageName(f.Function)

		// If the caller isn't part of this package, we're done
		if pkg != logrusPackage {
			return &f //nolint:scopelint
		}
	}

	// if we got here, we failed to find the caller's context
	return nil
}

type GetCallerHook struct {
}

func (hook *GetCallerHook) Fire(entry *logrus.Entry) error {
	entry.Caller = getCaller()
	return nil
}

func (hook *GetCallerHook) Levels() []logrus.Level {
	return logrus.AllLevels
}
`

log := logrus.New()
log.AddHook(&GetCallerHook{})
pitaya.SetLogger(NewWithLogger(log))


This is my own temporary solution

**Comment by echo766** [comment]
`package log

import (
	"runtime"
	"strings"
	"sync"

	"github.com/sirupsen/logrus"
)

var (

	// qualified package name, cached at first use
	logrusPackage string

	// Positions in the call stack when tracing to report the calling method
	minimumCallerDepth int

	// Used for caller information initialisation
	callerInitOnce sync.Once
)

const (
	maximumCallerDepth     = 25
	knownLogrusFrames  int = 10
)

// getPackageName reduces a fully qualified function name to the package name
// There really ought to be to be a better way...
func getPackageName(f string) string {
	for {
		lastPeriod := strings.LastIndex(f, ".")
		lastSlash := strings.LastIndex(f, "/")
		if lastPeriod > lastSlash {
			f = f[:lastPeriod]
		} else {
			break
		}
	}

	return f
}

// getCaller retrieves the name of the first non-logrus calling function
func getCaller() *runtime.Frame {
	// cache this package's fully-qualified name
	callerInitOnce.Do(func() {
		pcs := make([]uintptr, maximumCallerDepth)
		_ = runtime.Callers(0, pcs)

		// dynamic get the package name and the minimum caller depth
		for i := 0; i < maximumCallerDepth; i++ {
			funcName := runtime.FuncForPC(pcs[i]).Name()
			if strings.Contains(funcName, "getCaller") {
				logrusPackage = getPackageName(funcName)
				break
			}
		}

		minimumCallerDepth = knownLogrusFrames
	})

	// Restrict the lookback frames to avoid runaway lookups
	pcs := make([]uintptr, maximumCallerDepth)
	depth := runtime.Callers(minimumCallerDepth, pcs)
	frames := runtime.CallersFrames(pcs[:depth])

	for f, again := frames.Next(); again; f, again = frames.Next() {
		pkg := getPackageName(f.Function)

		// If the caller isn't part of this package, we're done
		if pkg != logrusPackage {
			return &f //nolint:scopelint
		}
	}

	// if we got here, we failed to find the caller's context
	return nil
}

type GetCallerHook struct {
}

func (hook *GetCallerHook) Fire(entry *logrus.Entry) error {
	entry.Caller = getCaller()
	return nil
}

func (hook *GetCallerHook) Levels() []logrus.Level {
	return logrus.AllLevels
}
`

log := logrus.New()
log.AddHook(&GetCallerHook{})
pitaya.SetLogger(NewWithLogger(log))


This is my own temporary solution

**Comment by echo7666** [comment]
`package logrus

import (
	"git.musketeer-ar.com/framework/pitaya/logger/interfaces"
	"github.com/sirupsen/logrus"
)

type logrusImpl struct {
	logrus.FieldLogger
}

// New returns a new interfaces.Logger implementation based on logrus
func New() interfaces.Logger {
	log := logrus.New()
	return NewWithLogger(log)
}

// NewWithEntry returns a new interfaces.Logger implementation based on a provided logrus entry instance
// Deprecated: NewWithEntry is deprecated.
func NewWithEntry(logger *logrus.Entry) interfaces.Logger {
	return &logrusImpl{FieldLogger: logger}
}

// NewWithLogger returns a new interfaces.Logger implementation based on a provided logrus instance
// Deprecated: NewWithLogger is deprecated.
func NewWithLogger(logger *logrus.Logger) interfaces.Logger {
	return &logrusImpl{FieldLogger: logrus.NewEntry(logger)}
}

// NewWithFieldLogger returns a new interfaces.Logger implementation based on a provided logrus instance
func NewWithFieldLogger(logger logrus.FieldLogger) interfaces.Logger {
	return &logrusImpl{FieldLogger: logger}
}

func (l *logrusImpl) WithFields(fields map[string]interface{}) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithFields(fields)}
}

func (l *logrusImpl) WithField(key string, value interface{}) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithField(key, value)}
}

func (l *logrusImpl) WithError(err error) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithError(err)}
}
`
You can modify the "pitaya/logger/logrus/logrus. go" for the above way to temporary fix the bug

**Comment by echo7666** [comment]
> ```
>     l := logrus.New()
> l.SetReportCaller(true)
> l.Formatter = &logrus.TextFormatter{}
> l.SetLevel(logrus.InfoLevel)
> if *debug {
> 	l.SetLevel(logrus.DebugLevel)
> }
> logruswrapper.NewWithFieldLogger(l)
> pitaya.SetLogger(logruswrapper.NewWithFieldLogger(l))
> ```
> 
> Always locate in github.com/topfreegames/pitaya/blob/main/logger/logrus/logrus.go file

```
package logrus

import (
	"git.musketeer-ar.com/framework/pitaya/logger/interfaces"
	"github.com/sirupsen/logrus"
)

type logrusImpl struct {
	logrus.FieldLogger
}

// New returns a new interfaces.Logger implementation based on logrus
func New() interfaces.Logger {
	log := logrus.New()
	return NewWithLogger(log)
}

// NewWithEntry returns a new interfaces.Logger implementation based on a provided logrus entry instance
// Deprecated: NewWithEntry is deprecated.
func NewWithEntry(logger *logrus.Entry) interfaces.Logger {
	return &logrusImpl{FieldLogger: logger}
}

// NewWithLogger returns a new interfaces.Logger implementation based on a provided logrus instance
// Deprecated: NewWithLogger is deprecated.
func NewWithLogger(logger *logrus.Logger) interfaces.Logger {
	return &logrusImpl{FieldLogger: logrus.NewEntry(logger)}
}

// NewWithFieldLogger returns a new interfaces.Logger implementation based on a provided logrus instance
func NewWithFieldLogger(logger logrus.FieldLogger) interfaces.Logger {
	return &logrusImpl{FieldLogger: logger}
}

func (l *logrusImpl) WithFields(fields map[string]interface{}) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithFields(fields)}
}

func (l *logrusImpl) WithField(key string, value interface{}) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithField(key, value)}
}

func (l *logrusImpl) WithError(err error) interfaces.Logger {
	return &logrusImpl{FieldLogger: l.FieldLogger.WithError(err)}
}
```
You can modify the "pitaya/logger/logrus/logrus. go" for the above way to temporary fix the bug
