### ISSUE TITLE
About module and components init

### ISSUE THREAD

**Issue by Arstray** [topfreegames/pitaya#293]
I found that startModules() is located after startupComponents() in app.listen(). Is there any deep meaning in doing this? At present, most of our basic capabilities are encapsulated as modules, so operations such as cache initialization cannot be completed in the AfterInit life cycle of components. Or you can give me some suggestions for use in such scenarios, thank you.

**Comment by felipejfc** [comment]
The reason is that the serviceDiscovery is a module, if it registers before the handlers are registered we can have a racing condition where the server receives requests before it's ready to answer them. Closing this.
