### ISSUE TITLE
pitaya can provide common template for grafana？

### ISSUE THREAD

**Issue by majintao** [topfreegames/pitaya#296]

**Comment by long12310225** [comment]
I'm using pitaya and have already connected with Pramicius. I think I'll have to complete all the main logic of the server before I can start working on grafana. I'll upload a generic pitaya grafana configuration file
 
&nbsp;


Endless&nbsp;waltz
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月17日(星期五) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [topfreegames/pitaya] pitaya can provide common template for grafana？ (Issue #296)

**Comment by sandy1219** [comment]
> 

waitting for you   thanks

**Comment by bruce1125** [comment]
I have the same issue,I am wondering if I could get the template from  anyone or anywhere ?
Thank you very much.
