### ISSUE TITLE
viper_config.go key change

### ISSUE THREAD

**Issue by sandy1219** [topfreegames/pitaya#301]
viper_config.go   
the defaultsMap key "pitaya.metrics.periodicMetrics.period"  change to "pitaya.metrics.period" is better........

**Comment by sandy1219** [comment]
"pitaya.cluster.sd.etcd.syncserversparallelism" ----->"pitaya.cluster.sd.etcd.syncservers.parallelism"

**Comment by rsafonseca** [comment]
This has been addressed :)
