### ISSUE TITLE
requestID 

### ISSUE THREAD

**Issue by sandy1219** [topfreegames/pitaya#304]
1：handler.go  in func processMessage()
requestID := nuid.New(), requestID is a object

2：util.go in func CtxWithDefaultLogger
requestID := pcontext.GetFromPropagateCtx(ctx, constants.RequestIDKey)
this place got the requestID is not a string,so new 

1 fix:
requestID := nuid.New().Next()

**Comment by felipejfc** [comment]
fixed and will enter the next release. thanks
