### ISSUE TITLE
s.OnClose not   receives when the session is closed

### ISSUE THREAD

**Issue by ruifly2012** [topfreegames/pitaya#32]
the demo cluster room.go the s.OnClose not   receives when the session is closed

**Comment by felipejfc** [comment]
It doesn't, and it's because session.OnClose method only works in frontend servers (because there's no connection from the user to the backend server).
I'll remove this line from the example as it can me misleading. You should move the OnClose logic to a frontend server.

**Comment by felipejfc** [comment]
I'm closing the issue, reopen it if you want further details.
