### ISSUE TITLE
There is a panic that could interrupt graceful shutdown

### ISSUE THREAD

**Issue by bruce1125** [topfreegames/pitaya#333]
https://github.com/topfreegames/pitaya/blob/e3ef17b39599ce3afd7563113d0b41b3dcbfeec7/cluster/etcd_service_discovery.go#L607-L625

while ETCD revoking time out,but going done a few later,it would cause a panic because chan is already closed.

**Comment by haoyu234** [comment]
I've already submitted a push request, which should fix the problem. https://github.com/topfreegames/pitaya/pull/326
