### ISSUE TITLE
pitaya  compilation error in v2.11.0

### ISSUE THREAD

**Issue by chengroot** [topfreegames/pitaya#395]
Hello everybody !!
    When I upgraded to aceV2.11, I encountered an error when starting compilation.

    operating system:  windows 11.
    go version:  v1.22.1
    pitaya version:  v2.11.0

Error screenshot:    
![图片](https://github.com/topfreegames/pitaya/assets/31918286/15ccf71c-bddc-4884-a1f8-ec875294df66)

![图片](https://github.com/topfreegames/pitaya/assets/31918286/5c17a4d6-1de3-4214-aaa3-f42053f59d62)

**Comment by felipejfc** [comment]
Fixed on #v2.11.1
