### ISSUE TITLE
How do I receive http requests on the pitaya server

### ISSUE THREAD

**Issue by chen221260** [topfreegames/pitaya#403]
when i use 
http.ListenAndServe(fmt.Sprintf(":%d", 1600), nil)
it log error:
 tried to add an acceptor to a backend server
what should i do?

**Comment by felipejfc** [comment]
this error is not related to your HTTP server. as the log clearly pointed out, you tried to add a pitaya acceptor to a backend server. Remove the acceptor and it will work
