### ISSUE TITLE
More demos please!

### ISSUE THREAD

**Issue by wujianv5** [topfreegames/pitaya#76]
Hello, developers.

Google lead me here, and this project seems promising. I followed every steps in the readme and I can succesfully run the demo. Since I'm new to golang I need more specific instructions than in the readme and the online doc. So please give us more basic and detailed demos.

And another question is do you have any roadmap for this project? I hope it would be a long term active project, and I'd like to see more features coming out.

Thank you guys. Keep up good work!

**Comment by felipejfc** [comment]
Thanks for your feedback @wujianv5 

We are using pitaya to power a lot of production games, so we can asure you the project will be maintained in the future, but as andre pointed, this doesn't mean we will develop new features all the time, only when the need arises or someone requests it and we think it makes sense.

I'm closing this issue, feel free to reopen it in the future if you feel necessary.

best
