### ISSUE TITLE
Hi, can you support rudp protocol?

### ISSUE THREAD

**Issue by SteveCruise** [topfreegames/pitaya#78]
Many games use Reliable UDP, such as Tencent Game.
https://gcloud.qq.com/product/7

**Comment by andrehp** [comment]
That's an interesting feature to add, we will look into it

**Comment by felipejfc** [comment]
we could take a look at [kcp-go](https://github.com/xtaci/kcp-go), it seems to be very good and also has a c++ library that supports ios and android [here](https://github.com/xtaci/libkcp)
it would be trivial to add support to the server, but maybe not so trivial to do the same in libpitaya...

**Comment by SteveCruise** [comment]
Great! Thank you so much!
