### ISSUE TITLE
cannot use auth.callOpts

### ISSUE THREAD

**Issue by jmesyan** [topfreegames/pitaya#79]
env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/admin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/code"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rs/g895d51j2qjbkq2l0zxm7bym0000gn/T/go-build134005452=/tmp/go-build -gno-record-gcc-switches -fno-common"

run  make run-cluster-grpc-example-connector, show the error down:
make: *** No rule to make target `run-cluster-grpc-example-connector'.  Stop.
MacBook-Pro:testing admin$ cd ../
Book-Pro:examples admin$ cd ../
Book-Pro:pitaya admin$ make run-cluster-grpc-example-connector
# github.com/nats-io/nkeys
../../../../../nats-io/nkeys/strkey.go:92:17: undefined: ed25519.SeedSize
# github.com/coreos/etcd/clientv3
../../../../../coreos/etcd/clientv3/auth.go:116:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
../../../../../coreos/etcd/clientv3/auth.go:121:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
../../../../../coreos/etcd/clientv3/auth.go:126:100: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
../../../../../coreos/etcd/clientv3/auth.go:131:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
../../../../../coreos/etcd/clientv3/auth.go:136:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
../../../../../coreos/etcd/clientv3/auth.go:141:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
../../../../../coreos/etcd/clientv3/auth.go:146:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
../../../../../coreos/etcd/clientv3/auth.go:151:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
../../../../../coreos/etcd/clientv3/auth.go:156:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
../../../../../coreos/etcd/clientv3/auth.go:161:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.RoleAdd
../../../../../coreos/etcd/clientv3/auth.go:161:80: too many errors
# github.com/topfreegames/pitaya/protos
../../../protos/bind.pb.go:59:29: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/doc.pb.go:58:25: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/docmsg.pb.go:58:28: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/error.pb.go:60:27: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/error.pb.go:85:2: undefined: "github.com/gogo/protobuf/proto".RegisterMapType
../../../protos/kick.pb.go:58:29: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/kick.pb.go:102:32: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/msg.pb.go:91:25: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/protodescriptor.pb.go:59:37: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/protodescriptor.pb.go:103:31: undefined: "github.com/gogo/protobuf/proto".InternalMessageInfo
../../../protos/protodescriptor.pb.go:103:31: too many errors
make: *** [run-cluster-grpc-example-connector] Error 2

**Comment by andrehp** [comment]
Hi jmesyan, did you run `make setup` before running these commands?

**Comment by jmesyan** [comment]
yes,but show errors:
```
MacBook-Pro:pitaya admin$ make setup
The following errors occurred while deducing packages:
  * "golang.org/x/net/context": unable to deduce repository and source type for "golang.org/x/net/context": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/net/context?go-get=1": Get http://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:80: i/o timeout
  * "google.golang.org/grpc": unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/grpc?go-get=1": Get http://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:80: i/o timeout

validateParams: could not deduce external imports' project roots
make: *** [setup] Error 1

````
in china , i can' t visit the http://google.golang.org/grpc

**Comment by jmesyan** [comment]
i have solve the problem @andrehp
