### ISSUE TITLE
external port doesn't work on grpc mode

### ISSUE THREAD

**Issue by Henrod** [topfreegames/pitaya#80]
There is only one grpc server starting [here](https://github.com/topfreegames/pitaya/blob/master/cluster/grpc_rpc_server.go#L62). So the only scenario where external port works is when `grpc.port == grpc.externalport` on config. 

Maybe rethink if it's necessary to have internal port and external port. If it's, ensure that we can `go gs.grpcSv.Serve(lis)` with two different addresses for lis or we need to have two `*grpc.Server` on GRPCServer struct.

**Comment by felipejfc** [comment]
If I understood correctly this port would be used as a hack to do inter-cluster communication like we did with pomelo, if so, I don't agree with what you're saying, external port does not necessarily need to be ==port, it just have to be the port that the "proxy" we're using to reach the server is listening, like a loadbalancer port, right?

Regardless, I don't want us to have this hack at all in pitaya in the mid term. If one wants to communicate two servers it must ensure that all servers are reachable using port.

**Comment by Henrod** [comment]
Yes, actually that is the issue. Now we need to configure port == external-port, otherwise it won't work. 

So you think pitaya shouldn't have external-host too?
