### ISSUE TITLE
grpc for rpc client doesn't report metrics

### ISSUE THREAD

**Issue by Henrod** [topfreegames/pitaya#81]
Using nats as rpc client, ReportTimingFromCtx is called [here](https://github.com/topfreegames/pitaya/blob/master/cluster/nats_rpc_client.go#L175), but the same doesn't happen on Call method of GRPCClient.

**Comment by felipejfc** [comment]
fixed in c88be0c65c18a97046230fd5bfdc3da3c57e4fd0, reopen if you see any problem
