### ISSUE TITLE
pitaya does not support go.mod

### ISSUE THREAD

**Issue by arden** [topfreegames/pitaya#84]
when i'm use v0.7.5 in go.mod

```
require (
	github.com/topfreegames/pitaya v0.7.5
)
```

some errors below:

```
go: finding github.com/topfreegames/pitaya v0.7.5
go: github.com/topfreegames/pitaya@v0.7.5: unknown revision v0.7.5
go: error loading module requirements
```

when i'm use latest in go.mod

```
require (
	github.com/topfreegames/pitaya latest
)
```
that may be use v0.2.1 version.

Because you created 0.7.5 as released tag, not v0.7.5。

**Comment by felipejfc** [comment]
thanks for letting us know, you are right...

I've just pushed a v0.7.6 tag for fixing go.mod compatibility!
