### ISSUE TITLE
RPC and RPCTo: can not get session from context

### ISSUE THREAD

**Issue by landbed** [topfreegames/pitaya#88]
connector

```
pitaya.RPC(ctx, "room.room.messageremote", ret, msg)
```

room MessageRemote func
```
s := pitaya.GetSessionFromCtx(ctx)
```

panic
```
ERRO[1040] pitaya/dispatch: interface conversion: interface {} is nil, not *session.Session  source=pitaya
```

**Comment by felipejfc** [comment]
hi @landbed, thanks for your interest in pitaya!

the reason of the panic is that you're calling GetSessionFromCtx in a context that comes from a RPC call from another server, server's do not have sessions, GetSessionFromCtx is meant to be used only on handlers.

still I think we should do better handling of this situation and return a better error.

**Comment by landbed** [comment]
@felipejfc 

Thank you for your response, I thought User RPC and Sys RPC have same behavior about context. how do you think if they have  same behavior? is there any way to get session data in this situation?

**Comment by felipejfc** [comment]
The reason that User RPC can't have the same behaviour as Sys RPC is that not all User RPCs are called from a handler, which means that you cannot assume that an user will be correlated to it so you can't have an user session associated to it, got it? 

if you need to send some session's information in a User RPC I suggest you send it in the argument.

best!

**Comment by landbed** [comment]
@felipejfc Thanks!
