### ISSUE TITLE
Always printing out "Read no packets, data: []"

### ISSUE THREAD

**Issue by ruifly2012** [topfreegames/pitaya#99]
![微信图片_20190425134739](https://user-images.githubusercontent.com/4121707/56712289-8b1d8600-6760-11e9-9bc6-4b5278192ab8.png)
websocket

**Comment by felipejfc** [comment]
Have you guys been able to solve this? @landbed @bytemode?

**Comment by felipejfc** [comment]
closed due to lack of response
